"""create document_registry

Revision ID: cee5a43c57cd
Revises: 8e3ad1b2a7e5
Create Date: 2026-07-23 00:34:18.233844

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cee5a43c57cd'
down_revision: Union[str, None] = '8e3ad1b2a7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('lc_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    document_registry = sa.table(
        "document_registry",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("industry", sa.String),
        sa.column("instrument_type", sa.String),
        sa.column("document_type", sa.String),
        sa.column("category", sa.String),
        sa.column("mandatory", sa.Boolean),
        sa.column("lc_required", sa.Boolean),
    )
    op.bulk_insert(
        document_registry,
        [
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "Drug Manufacturing License (Form 25/28)", "category": "Regulatory / Compliance", "mandatory": True, "lc_required": False},
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "Certificate of Pharmaceutical Product (CoPP)", "category": "Regulatory / Compliance", "mandatory": True, "lc_required": True},
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "WHO-GMP / Schedule-M Certificate", "category": "Regulatory / Compliance", "mandatory": True, "lc_required": True},
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "Certificate of Analysis (CoA)", "category": "Regulatory / Compliance", "mandatory": True, "lc_required": True},
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "Free Sale Certificate", "category": "Regulatory / Compliance", "mandatory": True, "lc_required": False},
            {"id": uuid.uuid4(), "industry": "Pharmaceuticals", "instrument_type": "Letter of Credit", "document_type": "Cold-Chain Temperature Certificate", "category": "Regulatory / Compliance", "mandatory": False, "lc_required": False},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM document_registry")
    op.drop_table('document_registry')
    # ### end Alembic commands ###
