"""create trades

Revision ID: 6fe85e53a2b7
Revises: cee5a43c57cd
Create Date: 2026-07-23 00:46:04.902999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe85e53a2b7'
down_revision: Union[str, None] = 'cee5a43c57cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lc_reference', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('exporter_org_id', sa.UUID(), nullable=False),
    sa.Column('buyer_org_id', sa.UUID(), nullable=False),
    sa.Column('issuing_bank_org_id', sa.UUID(), nullable=False),
    sa.Column('advising_bank_org_id', sa.UUID(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('incoterm', sa.String(), nullable=False),
    sa.Column('payment_term', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advising_bank_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['buyer_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['exporter_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['issuing_bank_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
